### PR TITLE
Support diff syntax highlighting

### PR DESCRIPTION
**Pull request by revin**
Yaks be shaved, this should take care of #64:

* The stock [highlights](https://github.com/atom/highlights) package we use for syntax highlighting doesn't include a grammar for diffs. Its existing grammars are mostly automatically converted from TextMate grammars, and TM _does_ have a diff one, so I converted it myself and published it to NPM as [atom-language-diff](https://www.npmjs.com/package/atom-language-diff), then added it as a dependency here.
* I discovered that the HTML sanitizer was wrecking the generated output. It turns out that the [highlights-tokens](https://www.npmjs.com/package/highlights-tokens) package, where we get a list of allowed class names, generates the token list by analyzing the `highlights` package's generated grammar objects. So I added a build step to `atom-language-diff` that generates a `tokens.json` we could use here. This PR pulls that into a separate module along with the stock `highlights-tokens` stuff so we can have a convenient place to add more in the future (**see note below**).
* That all seemed to work, so I added a couple of tests, and here we are.

**Note:** Unless I'm missing something, I believe the other non-stock languages we support for syntax highlighting (`atom-language-nginx`, `language-rust`, etc..) aren't going to make it past the sanitizing step without first going through a similar process of generating their lists of valid tokens. Those might be candidates for new Issues.

### CODE REVIEW

**Comment by zeke** [comment]
```diff
- no diff support
+ diff support!
```

**Comment by aredridel** [comment]
Wow. this looks awesome. Nice careful work there!

**Comment by ashleygwilliams** [comment]
this is awesome @revin !! merging

**Comment by jonathanmarvens** [comment]
Nice! LGTM :+1:!

**Comment by zeke** [comment]
Hey @revin how did you find out about github's support for diff syntax highlighting? I'm trying to find a GitHub page that explains it so I can add a link to the readme. I suspect few people know about this great feature of GFM.

**Comment by wooorm** [comment]
@zeke I think it's in the linguist repo, which if I remember correctly houses all there supported fenced code block flags!

**Comment by revin** [comment]
@zeke Honestly I didn't know about it until I read #64 :-P and then went hunting through the `highlights` package to see how it could be done

**Pull request merged**
