### PR TITLE
Allow a custom render function to be passed in options

### PR DESCRIPTION
**Pull request by djMax**
To allow custom configuration of markdown-it.

### CODE REVIEW

**Comment by zeke** [comment]
I like this idea. Can your bring the PR up to date with master, and remove the version change? My publishing workflow leaves that up to the [npm version](https://docs.npmjs.com/cli/version) command.

**Comment by djMax** [comment]
updated.

**Comment by ashleygwilliams** [comment]
hey! this PR has neither docs nor tests. it will need both to get merged. lemme know if i can help with that.

**Comment by ashleygwilliams** [comment]
hi @djMax !

in order to consider this PR for the 5.7 milestone, i need at least a section of the `README` that would explain how to use this.

then to merge, i would need this to be rebased, squashed, and also to include tests.

let me know if you need any help! thanks for contributing.

**Comment by ashleygwilliams** [comment]
if i don't have follow up on this in a week or so i fear i'll have to close unless someone wants to pick it back up.

**Comment by ashleygwilliams** [comment]
hi. closing as this is stale.

**Pull request closed without merging**
