### PR TITLE
Split unit tests into a series of smaller files

### PR DESCRIPTION
**Pull request by revin**
Per #122, this splits the tests into a bunch of smaller files.

I'm enough of a n00b at Node conventions that I don't know if it's generally accepted to create modules lacking a `module.exports`, but doing so keeps the code a little simpler. The test groups themselves were pretty well defined already, so this is mostly just a copy/paste job, plus top-of-file `require` stuff.

### CODE REVIEW

**Comment by revin** [comment]
This doesn't include the test changes from #100, so if that gets merged to master, I'll have to update the corresponding tests here as well.

**Comment by ashleygwilliams** [comment]
@revin would you prefer i merge this now or later? s'up to you :)

**Comment by revin** [comment]
There's a little bit of effort either way, so I'd vote for sooner rather than later, if it's all the same to you. Go for it.

**Comment by ashleygwilliams** [comment]
ok! i'll merge this now. thanks :)

**Pull request merged**
