### PR TITLE
[WIP] 9.0.0

### PR DESCRIPTION
**Pull request by revin**
- [x] merge #223, #225, #227, #235, #242, #243 (and others...?)
- [x] merge #234
- Update the change log
  - [x] fix the release date at the top
  - [x] fix the version string for `highlights` in the Dependencies section
- [x] run `npm test` or `npm build` to update the browserify bundle, and add it to this PR
- [x] rebase this onto master
- [ ] squash
- [ ] publish as `next` (#245), then wait a week
- [ ] create the `v9.0.0` tag (don't forget to `git push --tag`)
- [ ] `npm publish`
- [ ] 💃

### CODE REVIEW

**Comment by ashleygwilliams** [comment]
ok i have merged nearly everything. am gonna do the .npmignore now

**Comment by ashleygwilliams** [comment]
ok, everything is merged now. i'm going to do the dist build now

**Comment by ashleygwilliams** [comment]
OK! i think now that #273 is merged we are *done* with what we were planning to do for 9.0.0. anything else we want to sneak in? otherwise, @revin let's start working through this checklist so we can be ready to cut a new (spooky) release for halloween! 🎃 👻

**Comment by revin** [comment]
Awesome! I think all that's really left is to make sure the README here gets updated with extra issues/PRs/contributors from recent work. And maybe triple check that the `dist` bundle is up to date, I guess.

🎉🎉🎉

**Comment by ashleygwilliams** [comment]
omg i just really mucked up this rebase. i'm sorry! ugghhhh whhyyy

**Comment by revin** [comment]
@ashleygwilliams I know you've been traveling recently; want me to tackle this? It looks like with the order everything is now, we can just rebase 110e7b5 onto the current master, then rebuild the `dist` bundle…I think 😄

**Comment by ashleygwilliams** [comment]
hey @revin - go for it! i'm catching up on stuff post-Russia and won't be able to get to this until later this week.

**Comment by revin** [comment]
All right, got it rebased. I held off squashing it (although I guess GH now supports "squash & merge" if we want to use that) until we have a release date for the changelog. All that's left before publishing is to make that change, so we can pull the trigger any time with about five minutes' worth of work.

**Comment by revin** [comment]
Never mind @ashleygwilliams I forgot we were going to do the pre-release tag publish thing (#245), so I just added the date as 2016-10-31, and we should probably publish that soon so we can have that as the real release date (assuming I understood you and that's what you'd wanted).

**Comment by ashleygwilliams** [comment]
yeah! let's do it. 🎃 👻

**Comment by ashleygwilliams** [comment]
💃

**Pull request merged**
