### PR TITLE
Add support for JSX syntax highlighting in code blocks

### LINKED ISSUE #395: JSX language support
As noted [here](https://github.com/facebook/prop-types/pull/78), jsx-annoted code blocks which are formatted correctly on github do not use syntax highlighting on npmjs.com.

### PR DESCRIPTION
**Pull request by revin**
This will add support for highlighting JSX code blocks, once [highlights#55](https://github.com/atom/highlights/pull/55) is merged upstream.

Fixes #395

### CODE REVIEW

**Comment by revin** [comment]
Marking as WIP for now since this is waiting on getting a version number from the `highlights` package.

**Comment by zeke** [comment]
> waiting on getting a version number from the `highlights` package.

Can you elaborate on what this means? Maybe I can help unblock.

**Comment by revin** [comment]
@zeke `highlights` doesn't support JSX yet, so I submitted a PR for it: https://github.com/atom/highlights/pull/55

Once that's merged, I can get the version number they publish, and fix up our dependencies here to match.

**Comment by bcoe** [comment]
@zeke @revin I've published `highlights@next`, would love you to take it for a spin and make sure it works as expected.

It would be good to also add a test for TypeScript, since we also landed this feature; once you're happy @revin I can work with you sometime soon to role the renderer out to npm.

**Comment by revin** [comment]
Turns out (which I forgot) that upgrading to highlights@^3 ends up breaking on node 4 because a transitive dependency uses JS `Proxy`. So it looks like we're stuck for now unless we decide to retire node 4 support.

@bcoe @ashleygwilliams thoughts?

**Comment by revin** [comment]
Looks like node 4 is EOL in April 2018. Just IMHO, personally I feel like JSX and TypeScript support are probably in more demand than node 4 is, over the next 9 months. Only a hunch though, not supported by data.

**Comment by bcoe** [comment]
the rendering service we're running at npm uses Node 6; I think we should land this, but bump the major -- adding support for JSX is huge.

**Comment by bcoe** [comment]
(will do so once tests pass).

**Pull request merged**
