### PR TITLE
bump markdown-it, fix npm/newww#631

### PR DESCRIPTION
**Pull request by stevemao**

### CODE REVIEW

**Comment by zeke** [comment]
Nice! Does the new version of markdown-it support multi-line HTML comments?

**Comment by stevemao** [comment]
```
Updated HTML blocks logic to CM 0.21 spec.
```

I think so.

**Comment by zeke** [comment]
Cool. Maybe we can persuade @jefflembeck or @bcoe to cut a new release.

**Comment by stevemao** [comment]
:+1:

**Comment by bcoe** [comment]
@zeke @stevemao, happy to; will sync up with @jefflembeck regarding it.

**Comment by stevemao** [comment]
Any news? This is pretty important. it fixes a common bug on the npm website :)

**Comment by Flet** [comment]
Looks like this PR can be closed... `markdown-it` was bumped to `^4.4.0` in a more recent commit: https://github.com/npm/marky-markdown/commit/00994f1d27362b2f27e1db1ca030b06f6148515e

**Comment by ashleygwilliams** [comment]
closing as this was bumped in https://github.com/npm/marky-markdown/commit/a54770526a84effccb978a3d2e4e03e2e69bc278

**Pull request closed without merging**
