### PR TITLE
support node versions 4 and 5

### PR DESCRIPTION
**Pull request by ashleygwilliams**
this is to help with https://github.com/npm/docs/pull/414

### CODE REVIEW

**Comment by ashleygwilliams** [comment]
for posterity, i followed a lot of this https://gist.github.com/omnus/6404505

**Comment by ashleygwilliams** [comment]
@soldair would you review + merge (if acceptable)? otherwise, could you suggest someone else. appreciate it - thanks!

**Comment by soldair** [comment]
lgtm! :sheep:

**Comment by ashleygwilliams** [comment]
@soldair should this be a minor version bump?

**Comment by soldair** [comment]
I think so.

**Comment by zeke** [comment]
I think @bcoe was working on a JS port of oniguruma, yes?

**Pull request merged**
