### PR TITLE
Allow whitespace between image/link labels and paths

### LINKED ISSUE #328: Allow whitespace inside links and images
Hello, I noticed that some shields from http://shields.io/ do not work. It displays like this: 

screen shot 2017-01-15 at 2 17 25 pm

I have tried multiple things, such as editing spacing, but it doesn't work. The shields display correctly on Github. Also, I looked at other issues, which said it was because the description was truncated, but I do not think this was truncated.

Thank you.
Andrew

### PR DESCRIPTION
**Pull request by revin**
It's kind of a bummer, but the type of looser parsing github does on links and images requires us to completely overwrite the markdown-it image and link rules. So, here it is.

Fixes #328

### CODE REVIEW

**Comment by revin** [comment]
Sure, I can take a look at doing that. I thought about it while I was working on this, and decided to be conservative and do as little modification to the original source as possible. But I think at least some of these loops that walk through the markdown can be refactored easily.

**Comment by ashleygwilliams** [comment]
<3<3<3 thank u. u r amazing. ur work is SUPER APPRECIATED.

**Comment by ashleygwilliams** [comment]
it occurs to me that if you want to just ships this as is we could add an issue for refactoring it later. and then that way we could 10.0 soon

**Comment by ashleygwilliams** [comment]
also i merged this out of order so i caused a conflict i'm sorrrrrrrrrrry 😩

**Comment by revin** [comment]
>it occurs to me that if you want to just ships this as is we could add an issue for refactoring it later. and then that way we could 10.0 soon

That's a good idea. I'd hate to hold everything up for what would be a patch-release-type change to the code. So I'd vote for that.

**Pull request merged**
