### PR TITLE
Async highlighting

### PR DESCRIPTION
**Pull request by soldair**
this is exposes the new highlights async methods for those that prefer non blocking fs calls

### CODE REVIEW

**Comment by ashleygwilliams** [comment]
hey @soldair what's the status on this?

**Comment by soldair** [comment]
I believe it works and is already released. I'll check :)

**Comment by ashleygwilliams** [comment]
@soldair can u comment with the status of this? thanks!

**Comment by ashleygwilliams** [comment]
this also appears to break marky on 4.1 => https://travis-ci.org/npm/marky-markdown/jobs/81693281

**Comment by soldair** [comment]
I'm going to need a little more time to understand the conflicts and make sure this matters as much as i thought it did =) but ill merge or close soon

**Comment by ashleygwilliams** [comment]
cool-- can you plz ping me before merge? probably gonna wanna squash this, and also i want to make sure it is added to the changelog

looks like you were aiming for a 6.0.0 release? are there breaking changes in this?

**Comment by soldair** [comment]
of course =)
no breaking changes just new apis

**Comment by ashleygwilliams** [comment]
hey @soldair this is 2 weeks+ stale now. thoughts on closing? the codebase has changed quite a bit in the last few months, will probably be easier to start a new PR anyways. lemme know!

**Comment by soldair** [comment]
ill close. if it' important i can rewrite it =).

it biggest benefit is that saves startup time loading language files

**Pull request closed without merging**
