### PR TITLE
[WIP] Support parsing of markdown syntax for emojis 

### PR DESCRIPTION
**Pull request by patriciarealini**
install & require [markdown-it-emoji](https://github.com/markdown-it/markdown-it-emoji) for Issue #59

### CODE REVIEW

**Comment by zeke** [comment]
:clap: :clap: :clap:

**Comment by patriciarealini** [comment]
thanks @zeke!

**Comment by patriciarealini** [comment]
The only thing, i think, i need to do to complete this PR is write the test. But i could use a little help understanding the formatting of the tests. 

@zeke I noticed that many of the commits on the `test/index.js` file were made by you, do you think you could walk me through the reasoning for the current format of the tests? I'm a little lost as to why they only compare the `.indexOf` the markdown to the `.length` of the DOM element that _should_ take it's place. I tried to mirror this test & it failed. (Which is totes fine! I would rather learn how to write better tests than just write one that passes cause it's the same as all the others. but i also wanted to stay as true as possible to the current state of affairs. trying to keep this contribution as seamless as possible...)

this is the direction i was going in...
```
    it('replaces markdown syntax for emoji with unicode for the emoji', function () {
      assert(~fixtures.github.indexOf(':sparkles:'))
      assert($('&#x2747;').length)
    })
```
the result i get is...
```
     SyntaxError: Unmatched selector: &#x2747;
```
even though I have tested the output in HTML for `:sparkles:` and it is `&#x2447;` (in alignment with the emoji unicode directory that markdown-it-emoji uses) please halp.

**Comment by soldair** [comment]
oh! i know the `$(" ")` only takes a css selector like an id `#id` or `.class` etc. 
you will have to compare the result text something like this i think
```
assert(~$.html().indexOf('&#x2747;'))
```

**Comment by zeke** [comment]
@soldair is on the right track there. To answer your question, @patriciarealini:

```js
it('removes classnames from elements', function () {
  assert(~fixtures.dirty.indexOf('class="xxx"'))
  assert(!$('.xxx').length)
})
```

The above code is ensuring that the given substring is **present in the fixture, but not present in the cheerio-generated DOM tree**. The `~` is the magical and not-very-intuitive [bitwise NOT](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_Operators?redirectlocale=en-US&redirectslug=JavaScript%2FReference%2FOperators%2FBitwise_Operators#Bitwise_NOT). It would work just as well (and be more clear) to do this:

```js
assert(fixtures.dirty.indexOf('class="xxx"') > -1)
```

or...

```js
const contains = require('lodash').contains
assert(contains(fixtures.dirty, 'class="xxx"')
```

**Comment by ashleygwilliams** [comment]
hey @patriciarealini i'm thinking i might grab this PR and see it though so we can merge it. i'd like to cut a new minor version today with the dep updates i did and this! thoughts?

**Comment by patriciarealini** [comment]
ya sounds good! @ashleygwilliams

**Comment by ashleygwilliams** [comment]
closing in favor of #87

**Pull request closed without merging**
