### PR TITLE
Insane

### PR DESCRIPTION
**Pull request by zeke**
An experiment in replacing http://npm.im/sanitize-html with http://npm.im/insane, which implements the same API but is designed to have a smaller browser footprint.

Tests are currently failing because:

```
  TypeError: Cannot call method 'some' of undefined
    at testUrl (/Users/z/n/marky-markdown/node_modules/insane/sanitizer.js:86:29)
```

### CODE REVIEW

**Comment by bevacqua** [comment]
Bump `insane` to `2.0.0`, and change `expectedFilter` in `lib/sanitize.js` into:

```js
filter: function(frame) {
  // Allow YouTube iframes
  if (frame.tag != 'iframe') return true;
  return String(frame.attrs.src).match(/^(https?:)?\/\/(www\.)?youtube\.com/)
}
```

**Comment by bevacqua** [comment]
Hey @zeke can I get some feedback as to why this wasn't merged? Thanks!

**Comment by zeke** [comment]
Hi @bevacqua. Unfortunately I no longer have commit access to this repository, and it doesn't appear to be actively maintained by anyone at npm. Please reopen a new PR for `insane` support if you wish to pursue it.

**Comment by bevacqua** [comment]
Oh, okay. I was just wondering. Thanks!

**Pull request closed without merging**
