### PR TITLE
add `aria-hidden=true` to adding headings

### LINKED ISSUE #290: add `aria-hidden=true` to deeplinks
GitHub does this, so we should do this.

(GHDTSWSDT)

ok yeah that acronym isn't great. lol.

### PR DESCRIPTION
**Pull request by ashleygwilliams**
fixes #290

### CODE REVIEW

**Comment by ashleygwilliams** [comment]
tests are not passing and i'm not sure why right now, ~work in progress~

**Comment by ashleygwilliams** [comment]
had to fix sanitize. this is read for review now

**Comment by revin** [comment]
Nice! Although #289 changes `deep-link` to `anchor` so I guess we need to change these tests for that now since I just merged the other one.

**Comment by ashleygwilliams** [comment]
@revin yeah i can fix that

**Comment by ashleygwilliams** [comment]
OK! @revin this should be good now

**Pull request merged**
