### PR TITLE
GitHub-style task lists

### PR DESCRIPTION
**Pull request by revin**
I'd intended to add this as part of the work I'm doing on the overall list parsing, but it's enough of a standalone thing that I decided to make it a separate PR since I'm overhauling that other work (again). In case you decide the request from #166 is worth implementing, here you go: now we take leading `[ ]` and `[x]` in list items and convert them into disabled checkboxes, same as GitHub does, as described at:

* [Task Lists in GFM: Issues/Pulls, Comments](https://github.com/blog/1375-task-lists-in-gfm-issues-pulls-comments)
* [Task lists in all markdown documents](https://github.com/blog/1825-task-lists-in-all-markdown-documents)

_Note: this is rebased on top of #164 for ease of merging later_

### CODE REVIEW

**Comment by zeke** [comment]
Love the idea. Would it make more sense as a `markdown-it` plugin, responsibility-wise?

**Comment by revin** [comment]
@zeke it is! It's just not in its own repo. Or is that what you meant, that it would be better if we maintained this one separately?

**Comment by zeke** [comment]
Yeah I meant a separate repo/package. Could be useful outside of marky-markdown town!

**Comment by revin** [comment]
Yeah that's a possibility. If we end up going all the way with issue #149 and turning _everything_ into markdown-it plugins, maybe it all should be split out as it happens? PR #164 is sort of in the same place. Marky would grow super tiny!

**Comment by revin** [comment]
ok @zeke I went your way and published the new stuff to npm as [markdown-it-task-lists](https://www.npmjs.com/package/markdown-it-task-lists), and updated this PR to pull it in rather than implement everything directly. I was lazy with the tests, however; they're substantially similar (read: basically the same) between repos :stuck_out_tongue:

**Pull request merged**
